# Generated by Django 6.0.3 on 2026-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'city')},
        ),
    ]
